export const ProductDataList = [
  {
    id: 1,
    price: 51000000,
    quantity: 1,
    title: "لپ تاپ acer مدل 2019",
    description: "توضیحات برای متن نمونه می باشد",
    display: ["large"],
    model: "acer",
    color: "red",
    categoryId: 1002,
  },
  {
    id: 2,
    price: 24000000,
    quantity: 1,
    title: "لپ تاپ acer مدل 2018",
    description: "توضیحات برای متن نمونه می باشد",
    model: "acer",
    display: ["medium"],
    color: "black",
    categoryId: 1002,
  },
  {
    id: 3,
    title: "لپ تاپ samsung مدل 2017",
    description: "توضیحات برای متن نمونه می باشد",
    price: 33000000,
    quantity: 1,
    model: "samsung",
    display: ["large", "medium", "small"],
    color: "silver",
    categoryId: 1002,
  },
  {
    id: 4,
    title: "لپ تاپ samsung مدل 2020",
    description: "توضیحات برای متن نمونه می باشد",
    price: 42200000,
    quantity: 1,
    model: "samsung",
    display: ["small", "medium"],
    color: "blue",
    categoryId: 1002,
  },
  {
    id: 5,
    title: "لپ تاپ asus مدل 2019",
    description: "توضیحات برای متن نمونه می باشد",
    price: 35000000,
    quantity: 1,
    display: ["medium", "large"],
    model: "asus",
    color: "black",
    categoryId: 1002,
  },
  {
    id: 6,
    title: "لپ تاپ asus مدل 2018",
    description: "توضیحات برای متن نمونه می باشد",
    price: 63000000,
    quantity: 1,
    display: ["small", "large"],
    model: "asus",
    color: "silver",
    categoryId: 1002,
  },
  {
    id: 7,
    title: "لپ تاپ asus مدل 2019",
    description: "توضیحات برای متن نمونه می باشد",
    price: 31000000,
    quantity: 1,
    display: ["small", "medium"],
    model: "asus",
    color: "silver",
    categoryId: 1002,
  },
  {
    id: 8,
    title: "لپ تاپ del مدل 2019",
    description: "توضیحات برای متن نمونه می باشد",
    price: 27000000,
    quantity: 1,
    display: ["small", "large"],
    model: "del",
    color: "white",
    categoryId: 1002,
  },
  {
    id: 9,
    title: "لپ تاپ canon مدل 2020",
    description: "توضیحات برای متن نمونه می باشد",
    price: 21500000,
    quantity: 1,
    display: ["small"],
    model: "canon",
    color: "yellow",
    categoryId: 1002,
  },
  {
    id: 10,
    title: "دوربین canon مدل 2018",
    description: "توضیحات برای متن نمونه می باشد",
    price: 12000000,
    quantity: 1,
    display: ["small", "medium"],
    model: "canon",
    color: "black",
    categoryId: 1001,
  },
];
